CREATE DATABASE Wingman;
GO

USE Wingman;
GO

CREATE TABLE Users(
	Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	Email NVARCHAR(100) UNIQUE NOT NULL,
	PasswordHash CHAR(84) NOT NULL,
	RefreshToken CHAR(44) NULL,
	RefreshTokenExpirationDateTimeUTC DATETIME2  NULL
);